keycdn.settings.*:
  type: config_entity
  label: 'KeyCDN Purger Settings'
  mapping:
    id:
      type: string
      translatable: false
    name:
      type: string
      translatable: false
    zone:
      type: string
      translatable: false
    api_key:
      type: string
      translatable: false
